# Generated by Django 5.2.13 on 2026-04-21 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('cumpleanios', models.DateField(blank=True, null=True)),
                ('estado_contacto', models.CharField(choices=[('reservo', 'Reservó'), ('no_reservo', 'No reservó'), ('no_contesto', 'No contestó')], default='no_contesto', max_length=20)),
                ('turno', models.CharField(choices=[('tarde', 'Tarde'), ('noche', 'Noche'), ('ambos', 'Tarde/Noche')], default='ambos', max_length=10)),
                ('aprobado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apodo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('a_confirmar', 'Falta confirmar'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('no_show', 'No asistió')], default='reservado', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.cliente')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.representante')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='reservas', to='core.voucher')),
            ],
        ),
    ]
