# Generated by Django 5.2.13 on 2026-05-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-hora_inicio']},
        ),
    ]
