# Generated by Django 5.2.13 on 2026-05-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
    ]
