# Generated by Django 5.2.13 on 2026-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reserva_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas_reales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
