# Generated by Django 5.2.13 on 2026-05-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserva_cantidad_personas_reales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_entrada',
            field=models.CharField(choices=[('free_con_representante', 'Free con representante'), ('free_sin_representante', 'Free sin representante'), ('cobrada_con_consumible', 'Cobrada con consumible'), ('cobrada_sin_consumible', 'Cobrada sin consumible')], default='free_sin_representante', max_length=35),
        ),
    ]
