# Generated by Django 5.2.13 on 2026-05-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_tipo_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_entrada',
            field=models.CharField(choices=[('free', 'Free'), ('cobrada_con_consumible', 'Cobrada con consumible'), ('cobrada_sin_consumible', 'Cobrada sin consumible')], default='free', max_length=35),
        ),
        migrations.CreateModel(
            name='AsistenciaRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.representante')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('free', 'Free'), ('cobrada_con_consumible', 'Cobrada con consumible'), ('cobrada_sin_consumible', 'Cobrada sin consumible')], max_length=35)),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='core.representante')),
            ],
        ),
    ]
