# Generated by Django 5.2.13 on 2026-05-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reserva_tipo_entrada_asistenciarepresentante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciarepresentante',
            name='hora_egreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciarepresentante',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='asistenciarepresentante',
            constraint=models.UniqueConstraint(fields=('representante', 'fecha'), name='unique_asistencia_por_dia'),
        ),
    ]
