# Generated by Django 5.2.13 on 2026-05-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_asistenciarepresentante_hora_egreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciarepresentante',
            name='acompañantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
