# Generated by Django 5.2.13 on 2026-06-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asistenciarepresentante_acompañantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apodo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEmbajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_egreso', models.TimeField(blank=True, null=True)),
                ('acompañantes', models.PositiveIntegerField(default=0)),
                ('embajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.embajador')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('embajador', 'fecha'), name='unique_asistencia_embajador_por_dia')],
            },
        ),
    ]
