# Generated by Django 5.2.13 on 2026-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_embajador_asistenciaembajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='vouchers',
            field=models.ManyToManyField(blank=True, related_name='entradas', to='core.voucher'),
        ),
    ]
