# Generated by Django 5.2.13 on 2026-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_entrada_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='tipo',
            field=models.CharField(choices=[('free', 'Free'), ('cobrada_con_consumible', 'Cobrada con consumible'), ('cobrada_sin_consumible', 'Cobrada sin consumible'), ('a_bailar', 'A bailar'), ('a_cenar', 'A cenar')], max_length=35),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_entrada',
            field=models.CharField(choices=[('free', 'Free'), ('cobrada_con_consumible', 'Cobrada con consumible'), ('cobrada_sin_consumible', 'Cobrada sin consumible'), ('a_bailar', 'A bailar'), ('a_cenar', 'A cenar')], default='free', max_length=35),
        ),
    ]
