# Generated by Django 5.2.13 on 2026-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_entrada_tipo_alter_reserva_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('qr', 'QR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_consumible',
            field=models.CharField(blank=True, choices=[('hombre', 'Consumible Hombre'), ('mujer', 'Consumible Mujer')], max_length=10, null=True),
        ),
    ]
